# Generated by Django 5.2 on 2025-05-16 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lichkham',
            table='lich_kham',
        ),
    ]
