# Generated by Django 5.2 on 2025-05-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_lichkham_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichkham',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
