# Generated by Django 5.2 on 2025-05-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_lichkham_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichkham',
            name='activation_token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
