# Generated by Django 5.2 on 2025-05-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_lichkham_activation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichkham',
            name='type',
            field=models.IntegerField(choices=[(0, 'Chưa xác nhận'), (1, 'Đã xác nhận')], default=0),
        ),
    ]
