# Generated by Django 5.2 on 2025-05-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_lichkham_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lichkham',
            name='type',
            field=models.IntegerField(choices=[(0, 'Chưa xác nhận'), (1, 'Đã xác nhận'), (2, 'Đã hủy')], default=0),
        ),
    ]
