# Generated by Django 5.2 on 2025-05-20 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_avatar_userprofile_chuc_vu_and_more'),
        ('appointment', '0007_alter_lichkham_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trang_thai', models.IntegerField(choices=[(0, 'Chưa xử lý'), (1, 'Đã xác nhận'), (2, 'Đã từ chối')], default=0)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'type': 1}, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
                ('lich_kham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.lichkham')),
            ],
            options={
                'unique_together': {('doctor', 'lich_kham')},
            },
        ),
        migrations.AddField(
            model_name='lichkham',
            name='doctors',
            field=models.ManyToManyField(related_name='appointments', through='appointment.DoctorAppointment', to='accounts.userprofile'),
        ),
    ]
