# Generated by Django 5.2 on 2025-05-26 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_doctorappointment_lichkham_doctors'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctorappointment',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='doctorappointment',
            table='doctor_appointments',
        ),
    ]
