# Generated by Django 5.2 on 2025-05-27 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_avatar_userprofile_chuc_vu_and_more'),
        ('appointment', '0009_alter_doctorappointment_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenhAn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_kham', models.DateField(auto_now_add=True)),
                ('chuan_doan', models.TextField()),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('bac_si', models.ForeignKey(blank=True, limit_choices_to={'type': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benh_an_bac_si', to='accounts.userprofile')),
                ('benh_nhan', models.ForeignKey(limit_choices_to={'type': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='benh_an_benh_nhan', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Bệnh án',
                'verbose_name_plural': 'Danh sách bệnh án',
                'db_table': 'benh_an',
            },
        ),
        migrations.CreateModel(
            name='BenhAnChiTiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trieu_chung', models.TextField()),
                ('ket_qua_xet_nghiem', models.TextField(blank=True, null=True)),
                ('don_thuoc', models.TextField(blank=True, null=True)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('benh_an', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='appointment.benhan')),
            ],
            options={
                'verbose_name': 'Chi tiết bệnh án',
                'verbose_name_plural': 'Chi tiết bệnh án',
                'db_table': 'benh_an_detail',
            },
        ),
    ]
