# Generated by Django 5.2 on 2025-05-27 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_benhan_benhanchitiet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='benhan',
            name='benh_nhan',
            field=models.ForeignKey(limit_choices_to={'type': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='benh_an_benh_nhan', to=settings.AUTH_USER_MODEL),
        ),
    ]
