# Generated by Django 5.2 on 2025-05-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0011_alter_benhan_benh_nhan'),
    ]

    operations = [
        migrations.AddField(
            model_name='benhanchitiet',
            name='anh_benh_an',
            field=models.ImageField(blank=True, null=True, upload_to='benh_an_images/', verbose_name='Ảnh bệnh án'),
        ),
    ]
