# Generated by Django 5.2 on 2025-05-27 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0012_benhanchitiet_anh_benh_an'),
    ]

    operations = [
        migrations.AddField(
            model_name='benhan',
            name='lich_kham',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benh_an_lich_kham', to='appointment.lichkham'),
        ),
    ]
