# Generated by Django 5.2 on 2025-05-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_activation_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Quản trị viên'), (1, 'Bác sĩ'), (2, 'Bệnh nhân')], default=2),
        ),
    ]
