# Generated by Django 5.2 on 2025-05-20 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_type'),
        ('chuyen_khoa', '0002_alter_chuyenkhoa_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='chuyen_khoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chuyen_khoa.chuyenkhoa', verbose_name='Chuyên khoa'),
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profile',
        ),
    ]
