# Generated by Django 5.2 on 2025-05-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_chuyen_khoa_alter_userprofile_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='chuc_vu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chức vụ'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hoc_vi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Học vị'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kinh_nghiem',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Số năm kinh nghiệm'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tuoi',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tuổi'),
        ),
    ]
