# Generated by Django 5.2 on 2025-05-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChuyenKhoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_chuyen_khoa', models.CharField(max_length=10, unique=True, verbose_name='Mã chuyên khoa')),
                ('ten_chuyen_khoa', models.CharField(max_length=100, verbose_name='Tên chuyên khoa')),
                ('mo_ta', models.TextField(blank=True, null=True, verbose_name='Mô tả chuyên khoa')),
            ],
            options={
                'verbose_name': 'Chuyên khoa',
                'verbose_name_plural': 'Các chuyên khoa',
                'ordering': ['ten_chuyen_khoa'],
            },
        ),
    ]
