# Generated by Django 5.2 on 2025-05-16 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chuyen_khoa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chuyenkhoa',
            table='chuyen_khoa',
        ),
    ]
